---
name: Hellow workflow
on:
  push:
    branches:
      - main
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hellow to all
        run: echo "Hey all"
      - name: Say hello to username
        run: echo "Hellow $user"

